import type { Opportunity } from './types'

export const OPPORTUNITIES: Opportunity[] = [
  {
    id: 'sch-vidyalaxmi',
    kind: 'scholarship',
    title: 'PM Vidyalaxmi Support',
    tamil: 'கல்வித்தொகை',
    department: 'Ministry of Education',
    summary: 'Interest-subvention education support for eligible higher-education students.',
    benefit: '₹50,000 / year',
    slaDays: 15,
    rules: {
      minAge: 17,
      maxAge: 30,
      locations: ['Tamil Nadu'],
      occupations: ['Student'],
      educationIncludes: ['B.E', 'B.Tech', 'Diploma', 'CSE'],
      maxIncome: 800000,
      requiredDocs: ['Aadhaar', 'Income Certificate', 'Marksheet'],
    },
  },
  {
    id: 'sch-minority',
    kind: 'scholarship',
    title: 'State Minority Scholarship',
    department: 'Department of Minorities Welfare',
    summary: 'Tuition and maintenance support for eligible students.',
    benefit: '₹20,000 / year',
    slaDays: 12,
    rules: {
      minAge: 16,
      maxAge: 35,
      locations: ['Tamil Nadu'],
      occupations: ['Student'],
      maxIncome: 250000,
      requiredDocs: ['Aadhaar', 'Income Certificate', 'Community Certificate'],
    },
  },
  {
    id: 'scheme-laptop',
    kind: 'scheme',
    title: 'Tamil Nadu Free Laptop Scheme',
    department: 'Department of Higher Education',
    summary: 'Devices for eligible college students with attendance requirements.',
    benefit: 'Laptop device',
    slaDays: 20,
    rules: {
      minAge: 17,
      maxAge: 25,
      locations: ['Tamil Nadu'],
      occupations: ['Student'],
      educationIncludes: ['College', 'B.E', 'B.Tech', 'Diploma'],
      requiredDocs: ['Aadhaar', 'College ID'],
    },
  },
  {
    id: 'scheme-magalir',
    kind: 'scheme',
    title: 'Kalaignar Magalir Urimai',
    department: 'Social Welfare Dept',
    summary: 'Monthly assistance for eligible women heads of household.',
    benefit: 'Monthly DBT',
    slaDays: 10,
    rules: {
      minAge: 21,
      locations: ['Tamil Nadu'],
      occupations: ['Homemaker', 'Self-employed', 'Farmer'],
      requiredDocs: ['Aadhaar', 'Income Certificate'],
    },
  },
  {
    id: 'course-python',
    kind: 'course',
    title: 'Advanced Python & AI Coding',
    department: 'Naan Mudhalvan',
    summary: 'Free self-paced coding path for students entering IT roles.',
    benefit: 'Free course · 6 weeks',
    slaDays: 7,
    rules: {
      occupations: ['Student', 'Looking for a job'],
      requiredSkills: [],
      requiredDocs: [],
    },
  },
  {
    id: 'course-powerbi',
    kind: 'course',
    title: 'Free Power BI Course',
    department: 'Skill Development Board',
    summary: 'Closes a common gap for analyst internships.',
    benefit: 'Free course · 4 weeks',
    slaDays: 7,
    rules: {
      occupations: ['Student', 'Looking for a job'],
      requiredDocs: [],
    },
  },
  {
    id: 'int-data',
    kind: 'internship',
    title: 'Junior Data Analyst Internship',
    department: 'Industry partner · Madurai / Remote',
    summary: 'Profile-matched internship. Skills should align with analyst work — not a job guarantee.',
    benefit: '₹15,000 / month',
    slaDays: 14,
    rules: {
      occupations: ['Student', 'Looking for a job'],
      requiredSkills: ['Python', 'Excel', 'SQL'],
      requiredDocs: ['Aadhaar', 'Resume'],
    },
  },
  {
    id: 'int-react',
    kind: 'internship',
    title: 'Junior React Dev Intern',
    department: 'Industry partner · Madurai / Remote',
    summary: 'Frontend internship aligned with CSE students.',
    benefit: '₹15,000 / month',
    slaDays: 14,
    rules: {
      occupations: ['Student', 'Looking for a job'],
      educationIncludes: ['CSE', 'B.E', 'B.Tech'],
      requiredSkills: ['Python'],
      requiredDocs: ['Aadhaar'],
    },
  },
  {
    id: 'job-nm',
    kind: 'job',
    title: 'Naan Mudhalvan placement track',
    department: 'Skill Development Board',
    summary: 'Campus-linked industry roles. Match indicates alignment, not selection.',
    benefit: 'Placement track',
    slaDays: 21,
    rules: {
      occupations: ['Student', 'Looking for a job'],
      locations: ['Tamil Nadu'],
      requiredDocs: ['Aadhaar', 'Marksheet'],
    },
  },
  {
    id: 'svc-community',
    kind: 'service',
    title: 'Community Certificate',
    department: 'Revenue Department',
    summary: 'Apply or renew a community certificate through assisted e-Sevai flow.',
    benefit: 'Certificate',
    slaDays: 15,
    rules: {
      locations: ['Tamil Nadu'],
      requiredDocs: ['Aadhaar'],
    },
  },
  {
    id: 'health-cmchis',
    kind: 'healthcare',
    title: 'CMCHIS Health Cover',
    department: 'Health Department',
    summary: 'Chief Minister’s Comprehensive Health Insurance enrolment check.',
    benefit: 'Health cover',
    slaDays: 10,
    rules: {
      locations: ['Tamil Nadu'],
      maxIncome: 500000,
      requiredDocs: ['Aadhaar', 'Income Certificate'],
    },
  },
]

export const DEFAULT_PROFILE = {
  name: 'Priya Lakshmi',
  phone: '9876543210',
  age: 19,
  location: 'Tamil Nadu',
  education: 'B.E CSE',
  occupation: 'Student',
  income: 150000,
  skills: ['Python', 'Excel'],
  interests: ['IT', 'Scholarships', 'Internships'],
  careerInterest: 'Data Analyst',
  documents: {
    Aadhaar: 'verified',
    Marksheet: 'uploaded',
    'Income Certificate': 'missing',
    'Community Certificate': 'uploaded',
    'College ID': 'uploaded',
    Resume: 'missing',
  },
  consentShare: true,
  consentNotify: true,
  consentTerms: true,
} as const
